import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'en' | 'ta';

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (text: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

// Comprehensive English to Tamil translation dictionary
const translationDictionary: Record<string, string> = {
  // Navigation Sidebar
  'Overview Dashboard': 'கண்காணிப்பு டாஷ்போர்டு',
  'Paddy Entry': 'நெல் வரவுப் பதிவேடு',
  'Paddy Purchase': 'நெல் கொள்முதல் பில்',
  'Milling & Stock': 'அரைவை & இருப்பு',
  'Quality & Finance': 'தரம் & நிதிப் பேரேடு',
  'Labor & Wages': 'தொழிலாளர் & கூலி',
  'Voice & Insights': 'செயல்பாட்டு நுண்ணறிவு',
  'Systems & Analytics': 'அமைப்புகள் & பகுப்பாய்வு',
  'Mill Manager Account': 'ஆலை மேலாளர் கணக்கு',
  'Active Workspace': 'செயலில் உள்ள பணித்தளம்',
  
  // Tab Titles
  'Paddy Entry Register': 'நெல் வரவுப் பதிவேடு',
  'Paddy Purchase Bills': 'நெல் கொள்முதல் பில்கள்',
  'Milling Batches & Stock Logs': 'அரைவை தொகுதிகள் & இருப்பு பதிவுகள்',
  'Quality Logs & Finance Ledger': 'தரக் கட்டுப்பாட்டு பதிவுகள் & நிதிப் பேரேடு',
  'Labor Wages & Attendance Tracker': 'தொழிலாளர் ஊதியம் & வருகைப் பதிவு',
  'Executive Insights Desk': 'செயல்பாட்டு நுண்ணறிவு பிரிவு',
  'Overview Dashboard Title': 'கண்காணிப்பு டாஷ்போர்டு',

  // Dashboard Stats
  'Live Milling Overview': 'நேரடி அரைவை கண்ணோட்டம்',
  'Paddy Stock (Bags)': 'நெல் இருப்பு (மூட்டைகள்)',
  'Rice Stock (Bags)': 'அரிசி இருப்பு (மூட்டைகள்)',
  'Unprocessed arrivals': 'செயலாக்கப்படாத நெல் வரவுகள்',
  'Active Milling Batches': 'செயலில் உள்ள அரைவை தொகுதிகள்',
  'Total Dispatched Today': 'இன்று அனுப்பப்பட்ட மொத்த அரிசி',
  'Paddy Arrivals Trend': 'நெல் வரவு போக்கு',
  'Paddy Stocks by Variety': 'நெல் ரகம் வாரியாக இருப்பு',
  'Rice Storage Balances': 'அரிசி சேமிப்பக இருப்பு விவரம்',
  'Live Milling Queue & Dispatch': 'அரைவை வரிசை & வாகன அனுப்புதல்',
  'Paddy Storage Balances': 'நெல் சேமிப்பக இருப்பு விவரம்',
  'Moisture': 'ஈரப்பதம்',
  'Moisture Average': 'சராசரி ஈரப்பதம்',
  
  // Common terms / Table columns
  'Supplier': 'விற்பனையாளர்/விவசாயி',
  'Supplier Name': 'விற்பனையாளர் பெயர்',
  'Variety': 'நெல் ரகம்',
  'Paddy Variety': 'நெல் ரகம்',
  'Lorry No': 'லாரி எண்',
  'Lorry Number': 'லாரி எண்',
  'Net Wt': 'நிகர எடை',
  'Net Weight': 'நிகர எடை',
  'Net Weight (Kg)': 'நிகர எடை (கிலோ)',
  'Status': 'நிலை',
  'Bags': 'மூட்டைகள்',
  'Bag Count': 'மூட்டைகளின் எண்ணிக்கை',
  'Driver Mobile': 'ஓட்டுனர் அலைபேசி',
  'Actions': 'செயல்கள்',
  'Dispatched': 'அனுப்பப்பட்டது',
  'Milling': 'அரைவை',
  'Storage Location': 'சேமிப்பு இடம்',
  'Storage Destination': 'சேமிப்பு இலக்கு',
  'Milling Progress': 'அரைவை முன்னேற்றம்',
  'In Progress': 'செயல்பாட்டில் உள்ளது',
  'Completed': 'முடிவடைந்தது',
  'Pending Rec': 'ஒப்பீடு தேவை',
  'Reconciled': 'ஒப்பிடப்பட்டது',
  'Gross Weight (Kg)': 'மொத்த எடை (கிலோ)',
  'Tare Weight (Kg)': 'வெற்று வண்டி எடை (கிலோ)',
  'Date': 'தேதி',
  'Arrival Date': 'வந்த தேதி',
  'Time': 'நேரம்',

  // Buttons & Actions
  'New Paddy Arrival': 'புதிய நெல் வரவுப் பதிவு',
  'Save Arrival Entry': 'வரவுப் பதிவைச் சேமி',
  'Clear Form': 'படிவத்தை அழி',
  'Search by supplier or lorry...': 'விற்பனையாளர் அல்லது லாரி எண் மூலம் தேடுக...',
  'Paddy Arrival Ledger': 'நெல் வரவுப் பதிவேடு',
  'Edit': 'திருத்து',
  'Delete': 'நீக்கு',
  'Edit Entry': 'பதிவைத் திருத்து',
  'Save Invoice': 'பில்லைச் சேமி',
  'Update Purchase Invoice': 'கொள்முதல் பில்லைப் புதுப்பி',
  'Search purchases (supplier/lorry)...': 'கொள்முதல் பில்களைத் தேடுக...',
  'Procurement Analysis Note': 'கொள்முதல் பகுப்பாய்வுக் குறிப்பு',
  'Copy Previous Row': 'முந்தைய வரியை நகலெடு',
  'Print Selected': 'அச்சிடு',
  'Bulk Delete': 'ஒட்டுமொத்தமாக நீக்கு',
  'Save': 'சேமி',
  'Copy': 'நகலெடு',
  'PDF': 'PDF அச்சிடு',
  'Cancel': 'ரத்துசெய்',
  'Action': 'செயல்',
  'Submit': 'சமர்ப்பி',
  'Search': 'தேடுக',
  'Add Supplier': 'விற்பனையாளரைச் சேர்',
  'Add Variety': 'புதிய ரகம் சேர்',

  // Paddy Purchase Form Sections
  'Reconcile Paddy Entry Arrival': '1. நெல் வரவை ஒப்பிட்டுச் சரிபார்',
  'Primary Paddy variety weight & Rate': '2. முதன்மை நெல் ரக எடை & விலை',
  'Freight, Handling Charges & Payouts': '3. வண்டி வாடகை, கையாளுதல் கட்டணம் & கொடுப்பனவுகள்',
  'Select unsaved arrival entry': 'சேமிக்கப்படாத வரவுப் பதிவைத் தேர்ந்தெடுக்கவும்',
  'Multiple Loads': 'பல சுமைகள்',
  'Multiple Loads:': 'பல சுமைகள்:',
  'Second Item Option': 'இரண்டாவது ரக விருப்பம்',
  'Second Item Option:': 'இரண்டாவது ரக விருப்பம்:',
  'Extra Loads from Same Supplier': 'அதே விற்பனையாளரிடமிருந்து கூடுதல் சுமைகள்',
  'Dry Yield Recovery Analysis': 'உலர் விளைச்சல் மீட்பு பகுப்பாய்வு',
  'Average Moisture': 'சராசரி ஈரப்பதம்',
  'Lorry Freight / Rent': 'லாரி வாடகை (வண்டி வாடகை)',
  'Handling Charges (Unloading)': 'இறக்குமதி கையாளுதல் கட்டணம்',
  'Brokerage Commission': 'தரகு கமிஷன்',
  'Total Amount Paid Now': 'இப்போது செலுத்தப்பட்ட தொகை',
  'Payment Payout Status': 'கொடுப்பனவு நிலை',
  'Paid Now': 'செலுத்தப்பட்ட தொகை',
  'Rate per Bag': 'மூட்டைக்கான விலை (Rate/Bag)',
  'Rate per Ton/Quintal': 'குவிண்டால்/டன் விலை (Rate/Kg equivalent)',
  'Gross Amount': 'மொத்த தொகை',
  'Net Amount': 'நிகர தொகை',
  'Total Value': 'மொத்த மதிப்பு',
  
  // Stock and Production
  'Production Batch Controller': 'அரைவை உற்பத்தி தொகுதி கட்டுப்பாட்டாளர்',
  'Start New Batch': 'புதிய அரைவை தொகுதியைத் தொடங்கு',
  'Select Paddy Storage': 'நெல் சேமிப்பகத்தைத் தேர்ந்தெடுக்கவும்',
  'Paddy Input Quantity (Bags)': 'நெல் உள்ளீடு அளவு (மூட்டைகள்)',
  'Output Head Rice (Bags)': 'வெளியீடு தலை அரிசி (மூட்டைகள்)',
  'Output Broken Rice (Bags)': 'வெளியீடு குருணை அரிசி (மூட்டைகள்)',
  'Milling Status': 'அரைவை நிலை',
  'Active Batches': 'செயலில் உள்ள அரைவை தொகுதிகள்',
  'Historical Batches': 'கடந்த கால அரைவை தொகுதிகள்',
  'Input Paddy': 'உள்ளீடு நெல்',
  'Output Rice': 'வெளியீடு அரிசி',
  'Rice Storage': 'அரிசி சேமிப்பகம்',
  'Yield Recovery %': 'அரைவை மீட்பு சதவீதம் (%)',
  'Create Production Batch': 'அரைவை உற்பத்தித் தொகுதியை உருவாக்கு',
  'Stock Logs & Receipts': 'இருப்பு பதிவுகள் & ரசீதுகள்',
  'Dispatch Loading Tracker': 'விநியோகம் மற்றும் லாரி ஏற்றுதல் கண்காணிப்பு',
  'Log Dispatch Loading': 'புதிய லாரி ஏற்றப் பதிவைச் சேர்',
  'Log Dispatch': 'ஏற்றுதல் பதிவைச் சேமி',
  'Dispatch Register': 'ஏற்றுதல் பதிவேடு',
  'Available Paddy Stock': 'கிடைக்கக்கூடிய நெல் இருப்பு',
  'Available Rice Stock': 'கிடைக்கக்கூடிய அரிசி இருப்பு',
  'Paddy Inventory': 'நெல் சரக்கு இருப்பு',
  'Rice Inventory': 'அரிசி சரக்கு இருப்பு',

  // Quality and Finance
  'Quality Records Ledger': 'தரக் கட்டுப்பாட்டுப் பதிவேடு',
  'Log Quality Inspection': 'புதிய தரப் பரிசோதனையைப் பதிவுசெய்',
  'Inspection Date': 'பரிசோதனை தேதி',
  'Foreign Matter %': 'அயல் பொருட்கள் (%)',
  'Chalky Grains %': 'மாவுத்தன்மை அரிசி (%)',
  'Damaged / Discolored %': 'சேதமடைந்த / நிறமாற்றமடைந்த அரிசி (%)',
  'Moisture %': 'ஈரப்பதம் (%)',
  'Head Rice Recovery (HRR) %': 'முழு அரிசி மீட்பு (HRR) %',
  'Quality Evaluation': 'தர மதிப்பீடு',
  'Passed': 'தேர்ச்சி பெற்றது',
  'Needs Sorting': 'மறுசுழற்சி தேவை',
  'Rejected': 'நிராகரிக்கப்பட்டது',
  'Inspection Register': 'பரிசோதனைப் பதிவேடு',
  'Cashflow & Ledger Dashboard': 'நிதிப் பேரேடு & பணப்புழக்கக் கண்காணிப்பு',
  'Cashflow Ledger': 'பணப்புழக்கப் பேரேடு',
  'Log Transaction': 'புதிய நிதிப் பரிவர்த்தனையைப் பதிவுசெய்',
  'Transaction Type': 'பரிவர்த்தனை வகை',
  'Income (Sales, Payouts)': 'வருவாய் (விற்பனை/வரவுகள்)',
  'Expense (Purchases, Wages)': 'செலவு (கொள்முதல்/கூலி)',
  'Amount (₹)': 'தொகை (₹)',
  'Reference Details': 'குறிப்பு விவரங்கள்',
  'Save Transaction': 'பரிவர்த்தனையைச் சேமி',
  'Ledger List': 'நிதிப் பேரேட்டு பட்டியல்',
  'Summary Metrics': 'நிதிச் சுருக்க அளவீடுகள்',
  'Total Revenue': 'மொத்த வருவாய்',
  'Total Expenditures': 'மொத்த செலவினங்கள்',
  'Net Cash Margin': 'நிகர லாப வரம்பு',

  // Labor and Wages
  'Labor Force Directory': 'தொழிலாளர்கள் விபரக் குறிப்பேடு',
  'Add New Laborer': 'புதிய தொழிலாளரைச் சேர்',
  'Labor Category': 'தொழிலாளர் பிரிவு',
  'Milling Crew': 'அரைவைப் பிரிவு',
  'Loading / Unloading Crew': 'ஏற்றுதல் / இறக்குதல் பிரிவு',
  'Dryer Operations': 'உலர்த்திப் பிரிவு',
  'Maintenance / Electrician': 'பராமரிப்பு / மின்சார வல்லுநர்',
  'Daily Wage Rate (₹/day)': 'தினசரி கூலி விகிதம் (₹/நாள்)',
  'Save Employee Details': 'தொழிலாளர் விவரங்களைச் சேமி',
  'Wages & Attendance Tracker': 'வருகை மற்றும் தினசரி கூலி கண்காணிப்பு',
  'Attendance Date': 'வருகைப் பதிவு தேதி',
  'Mark Attendance & Calculate Daily Wages': 'தொழிலாளர் வருகை மற்றும் தினசரி கூலி கணக்கீடு',
  'Employee': 'தொழிலாளர்',
  'Mark Status': 'வருகை நிலை',
  'Daily Earned Wage': 'இன்றைய கூலி',
  'Save Attendance Sheet': 'வருகைப் பதிவேட்டைச் சேமி',
  'Weekly Attendance Report': 'வருகை மற்றும் கூலி அறிக்கை',
  'Present Days': 'வந்த நாட்கள்',
  'Absent Days': 'வராத நாட்கள்',
  'Total Wages Earned': 'மொத்த ஈட்டிய கூலி',
  'Mark Present': 'வருகை',
  'Mark Absent': 'விடுப்பு',
  'Half-Day': 'அரை நாள்',
  'Mark Half-Day': 'அரை நாள் வருகை',

  // Voice and Insights
  'AI Voice-Activated Executive Insights Desk': 'செயற்கை நுண்ணறிவு குரல்வழி செயல்பாட்டு நுண்ணறிவு பிரிவு',
  'Type or click Microphone to ask executive queries:': 'இயக்குநரின் கேள்விகளைக் கேட்க தட்டச்சு செய்யவும் அல்லது மைக்ரோஃபோனைக் கிளிக் செய்யவும்:',
  'Try asking: "What is the available stock of RNR variety?" or "Show total purchases this month."': 'கேட்டுப் பாருங்கள்: "RNR ரகத்தின் தற்போதைய இருப்பு எவ்வளவு?" அல்லது "இந்த மாத கொள்முதல் மதிப்பை காட்டு."',
  'Speak Now': 'பேசவும்',
  'Listening...': 'கேட்கிறது...',
  'Processing voice command...': 'குரல் கட்டளை செயலாக்கப்படுகிறது...',
  'AI Insights Desk': 'செயற்கை நுண்ணறிவு உதவிப் பிரிவு',
  'Interactive Voice Assistant': 'ஊடாடும் குரல் உதவியாளர்',
  'Send Query': 'கேள்வியை அனுப்பு',
  'Enter query...': 'கேள்வியைத் தட்டச்சு செய்க...',
  'Executive Summary Report': 'செயல்பாட்டு சுருக்க அறிக்கை',

  // UI details
  'Mill Manager': 'ஆலை மேலாளர்',
  'SKP Rice Mill': 'எஸ்.கே.பி அரிசி ஆலை',
  'SKP Admin': 'எஸ்.கே.பி நிர்வாகி',
  'Lorry Dispatch Receipt': 'லாரி ஏற்றுதல் விநியோக ரசீது',
  'Print Receipt': 'அச்சிடுக',
  'Close': 'மூடு',
  'Print Purchase Slip': 'கொள்முதல் சீட்டு அச்சிடு',
  'Print / Save PDF': 'அச்சிடு / PDF சேமி',
  'Date & Supplier': 'தேதி & விற்பனையாளர்',
  'Arriving Paddy Lorry Entry': 'லாரி நெல் வரவுப் பதிவு',
  'Enter lorry gross/tare weights, and allocate grain varieties into silos or storage yards.': 'லாரி எடை விவரங்களை உள்ளிட்டு, சேமிப்பு சிலோக்களுக்கு ஒதுக்கவும்.',
  'Operational Command Center': 'செயல்பாட்டு கட்டுப்பாட்டு மையம்',
  'loads': 'சுமைகள்',
  'bags': 'மூட்டைகள்',
  'parboiled batches': 'அரைவை தொகுதிகள்',
  'Today': 'இன்று',
  'Tons supplied': 'டன் வரவு',
  'Today Purchase': 'இன்றைய கொள்முதல்',
  'Today Processed': 'இன்றைய அரைவை',
  'Pending Supplier Balance': 'விவசாயிகள் நிலுவைத் தொகை',
  'Shipped Deliveries Today': 'இன்றைய அரிசி விநியோகம்',
  'Highest Volume Supplier': 'அதிகபட்ச கொள்முதல் விவசாயி',
  'Est. Gross Profit (Milling)': 'மதிப்பிடப்பட்ட அரைவை லாபம்',
  'Top Suppliers (By Supplied weight)': 'முன்னணி விவசாயிகள் (எடை அடிப்படையில்)',
  'Variety-wise Procurement (By weight)': 'ரகம் வாரியாக கொள்முதல் (எடை அடிப்படையில்)',
  'Live Stock & Payable Warnings': 'இருப்பு மற்றும் நிலுவை எச்சரிக்கைகள்',
  'Strategic Operations Summary': 'ஆலை செயல்பாட்டு சுருக்க உரை',
  'Stock balances and payables are in safe thresholds.': 'இருப்பு நிலவரங்கள் மற்றும் நிலுவைத் தொகைகள் பாதுகாப்பான வரம்பில் உள்ளன.',
  'Need purchase data': 'கொள்முதல் தரவு தேவை',

  // Voice & Insights Component
  'Voice-Enabled Sales Assistant': 'குரல்வழி விற்பனை உதவியாளர்',
  'Suggested Voice Format:': 'பரிந்துரைக்கப்பட்ட குரல் வடிவம்:',
  'Voice Text Capture': 'குரல் உரை பிடிப்பு',
  'Captured spoken text will print here...': 'பேசப்பட்ட உரை இங்கே அச்சிடப்படும்...',
  'Start Voice': 'குரலைத் தொடங்கு',
  'Stop': 'நிறுத்து',
  'Auto Fill Form': 'படிவத்தை தானாக நிரப்பு',
  'Clear': 'அழி',
  'Status:': 'நிலை:',
  'Sales draft compiler': 'விற்பனை வரைவுத் தொகுப்பாளர்',
  'Party Name': 'வாடிக்கையாளர் பெயர்',
  'Variety / Item': 'ரகம் / தயாரிப்பு',
  'No. of Bags': 'மூட்டைகளின் எண்ணிக்கை',
  'Rate per Bag (₹)': 'மூட்டைக்கான விலை (₹)',
  'Lorry No': 'லாரி எண்',
  'Due Days': 'தவணை நாட்கள்',
  'Phone / WhatsApp': 'அலைபேசி / வாட்ஸ்அப்',
  'Sales Date': 'விற்பனை தேதி',
  'Estimated Total Amount:': 'மதிப்பிடப்பட்ட மொத்த தொகை:',
  'Save Sales Draft': 'விற்பனை வரைவைச் சேமி',
  'Copy WhatsApp Note': 'வாட்ஸ்அப் குறிப்பை நகலெடு',
  'Saved Local Sales Drafts': 'சேமிக்கப்பட்ட விற்பனை வரைவுகள்',
  'Clear All': 'அனைத்தையும் அழி',
  'These drafts are saved to your browser session storage. You can verify and load them into customer invoicing modules later.': 'இந்த வரைவுகள் உங்கள் உலாவி சேமிப்பகத்தில் சேமிக்கப்படும். பின்னர் அவற்றை விநியோக தொகுதியில் ஏற்றலாம்.',
  'Date': 'தேதி',
  'Party': 'வாடிக்கையாளர்',
  'Variety': 'தயாரிப்பு ரகம்',
  'Bags': 'மூட்டைகள்',
  'Rate': 'விலை',
  'Total': 'மொத்தம்',
  'No sales drafts created yet. Try the voice input!': 'விற்பனை வரைவுகள் எதுவும் இன்னும் உருவாக்கப்படவில்லை. குரல் உள்ளீட்டைப் பயன்படுத்தவும்!',
  'Operational Insights Business Dashboard': 'செயல்பாட்டு நுண்ணறிவு வணிக டாஷ்போர்டு',
  'Ask simple questions about your mill database. The rule engine generates instant financial reports, supplier analyses, and stock recommendation logs.': 'உங்கள் ஆலைத் தரவுத்தளத்தைப் பற்றிய எளிய கேள்விகளைக் கேளுங்கள். விதிகளின் அடிப்படையில் உடனடி நிதி அறிக்கைகள், விவசாயிகள் பகுப்பாய்வு மற்றும் இருப்புப் பரிந்துரைகள் உருவாக்கப்படும்.',
  'Ask a Question': 'கேள்வி கேட்கவும்',
  'e.g., who is our best supplier?': 'எ.கா: சிறந்த விவசாயி யார்?',
  'Analyze': 'பகுப்பாய்வு செய்',
  'Reset': 'மீட்டமை',
  'Quick Reports': 'உடனடி அறிக்கைகள்',
  'Today Purchases': 'இன்றைய கொள்முதல்',
  'This Month Purchases': 'இந்த மாத கொள்முதல்',
  'Best Supplier': 'சிறந்த விவசாயி',
  'Variety Purchase': 'ரகம் வாரியான கொள்முதல்',
  'Pending Balances': 'நிலுவைத் தொகைகள்',
  'Paddy Stock Levels': 'நெல் இருப்பு அளவுகள்',
  'Paddy Reorder recommendation': 'நெல் மறு ஆர்டர் பரிந்துரை',
  'Milling Yield Batch': 'சிறந்த விளைச்சல் தொகுதி',
  'Milling Batches Month': 'இந்த மாத அரைவை',
  'Absent Workers Today': 'இன்று வராத தொழிலாளர்கள்',
  'Suggestion Note:': 'பரிந்துரைக் குறிப்பு:',

  // Extra missing keys
  'Pending': 'நிலுவையில் உள்ளது',
  'Paid': 'செலுத்தப்பட்டது',
  'Partial': 'பகுதி செலுத்தப்பட்டது',
  'All Purchase Status': 'அனைத்து கொள்முதல் நிலை',
  'Entry Only': 'வரவுப் பதிவு மட்டும்',
  'Saved to Purchase': 'கொள்முதலில் சேமிக்கப்பட்டது',
  'No matching paddy entries found.': 'பொருந்தக்கூடிய நெல் வரவுகள் எதுவும் இல்லை.',
  'Filter date': 'தேதியை வடிக்க',
  'Filter party': 'விவசாயியை வடிக்க',
  'Filter lorry': 'லாரியை வடிக்க',
  'Filter weight': 'எடையை வடிக்க',
  'Filter bags': 'மூட்டைகளை வடிக்க',
  'Filter variety': 'ரகத்தை வடிக்க',
  'Filter storage': 'சேமிப்பை வடிக்க',
  'Filter recon': 'ஒப்பீட்டை வடிக்க',
  'Global search (supplier / lorry)...': 'ஒட்டுமொத்த தேடல் (விற்பனையாளர்/லாரி)...',
  'Cancel Edit': 'திருத்தலை ரத்துசெய்',
  'Update Paddy Entry': 'நெல் வரவைப் புதுப்பி',
  'Save Paddy Entry': 'நெல் வரவைச் சேமி',
  'Record Opening Paddy Balances (Silos / Godowns)': 'ஆரம்ப நெல் இருப்புகளைப் பதிவுசெய்க (சிலோஸ் / கிடங்குகள்)',
  'Initialize stock that was already filled before tracking with this application.': 'இந்த செயலி மூலம் கண்காணிக்கும் முன் ஏற்கனவே நிரப்பப்பட்ட இருப்பை உள்ளிடவும்.',
  'Silo / Godown Storage': 'சிலோ / கிடங்கு சேமிப்பு',
  'Lot Supplier / Ref': 'தொகுதி விற்பனையாளர் / குறிப்பு',
  'Save Opening Stock': 'ஆரம்ப இருப்பைச் சேமி',
  'Silo & Yard Stock Transfers': 'சிலோ மற்றும் யார்டு இருப்பு இடமாற்றங்கள்',
  'Move paddy raw lots between yards or feed silos directly.': 'யார்டுகள் அல்லது சிலோக்களுக்கு இடையே நெல் இருப்பை நேரடியாக மாற்றவும்.',
  'Transfer Date': 'மாற்றப்பட்ட தேதி',
  'From Storage': 'இருந்து (மூல சேமிப்பு)',
  'Select source': 'மூலத்தைத் தேர்ந்தெடுக்கவும்',
  'Select variety': 'ரகத்தைத் தேர்ந்தெடுக்கவும்',
  'Available Bags': 'கிடைக்கக்கூடிய மூட்டைகள்',
  'To Storage SILO': 'சேரும் சிலோ (இலக்கு)',
  'Bags to Move': 'மாற்ற வேண்டிய மூட்டைகள்',
  'Transfer Remarks': 'மாற்றுக் குறிப்புகள்',
  'Save Stock Movement': 'இருப்பு மாற்றத்தைச் சேமி',
  'Combine multiple grain lots to fulfill the 600 paddy bags parboiled requirement, and transition them into head & broken rice products.': '600 நெல் மூட்டைகளின் தேவையைப் பூர்த்தி செய்ய பல நெல் தொகுதிகளை ஒன்றிணைத்து, அவற்றை முழு மற்றும் குருணை அரிசி தயாரிப்புகளாக மாற்றவும்.',
  'Start New Batch (Deduct Paddy Stock)': 'புதிய தொகுதியைத் தொடங்கு (நெல் இருப்பைக் கழி)',
  'Milling Start Date': 'அரைவை தொடக்க தேதி',
  'Batch ID / Process No': 'தொகுதி ஐடி / செயல்முறை எண்',
  'Target Batch size (Bags)': 'இலக்கு தொகுதி அளவு (மூட்டைகள்)',
  'Presteam Timing (Min)': 'அவித்தல் நேரம் (நிமிடங்கள்)',
  'Holding Tank Tempering (Min)': 'தொட்டி பதப்படுத்துதல் (நிமிடங்கள்)',
  'LCU Tank Tempering (Hours)': 'LCU தொட்டி பதப்படுத்துதல் (மணிநேரம்)',
  'Water Soaking (Hours)': 'தண்ணீர் ஊறவைத்தல் (மணிநேரம்)',
  'Combine Paddy Stocks for Batch': 'தொகுதிக்கான நெல் இருப்புகளை இணைக்கவும்',
  'Select Silo/Godown': 'சிலோ/கிடங்கைத் தேர்ந்தெடு',
  'Select storage': 'சேமிப்பைத் தேர்ந்தெடு',
  'Available Stock (Bags)': 'கிடைக்கக்கூடிய இருப்பு (மூட்டைகள்)',
  'Add bags from source': 'மூலத்திலிருந்து மூட்டைகளைச் சேர்',
  '+ Add Source Line': '+ மூல வரியைச் சேர்',
  'Paddy Bin': 'நெல் தொட்டி (பின்)',
  'Bags Added': 'சேர்க்கப்பட்ட மூட்டைகள்',
  'Total Selected Paddy:': 'தேர்ந்தெடுக்கப்பட்ட மொத்த நெல்:',
  'Start Milling Remarks': 'அரைவை குறிப்புகள்',
  'Start Production Batch': 'அரைவை உற்பத்தித் தொகுதியைத் தொடங்கு',
  '2️⃣ Complete Milling Output (Yield & Rice Bags Creation)': '2️⃣ அரைவை வெளியீட்டை முடித்தல் (அரிசி மூட்டைகள் உருவாக்கம்)',
  'Select In-Process Batch': 'செயல்பாட்டில் உள்ள தொகுதியைத் தேர்ந்தெடு',
  'Select batch': 'தொகுதியைத் தேர்ந்தெடு',
  'Completion Date': 'முடிவடைந்த தேதி',
  'Milled Batch No': 'அரைக்கப்பட்ட தொகுதி எண்',
  'Rice storage placement': 'அரிசி சேமிப்பக இடம்',
  'Head Rice Output (Bags 26kg)': 'முழு அரிசி வெளியீடு (26 கிலோ மூட்டைகள்)',
  'Broken Rice Output (Bags 26kg)': 'குருணை அரிசி வெளியீடு (26 கிலோ மூட்டைகள்)',
  'Final Moisture %': 'இறுதி ஈரப்பதம் %',
  'Milled Grade Quality': 'அரைக்கப்பட்ட அரிசி தரம்',
  'Good': 'நன்று',
  'Excellent': 'மிக நன்று',
  'Average': 'சராசரி',
  'Needs Check': 'சரிபார்க்கப்பட வேண்டும்',
  'Poststeaming Timing (Min)': 'இரண்டாம் அவித்தல் நேரம் (நிமிடங்கள்)',
  'Mechanical Drying Cycle (Hours)': 'இயந்திர உலர்த்தும் சுழற்சி (மணிநேரம்)',
  'Output Milling Remarks': 'வெளியீட்டு அரைவைக் குறிப்புகள்',
  'Complete Batch & Create Rice Stock': 'தொகுதியை முடித்து அரிசி இருப்பை உருவாக்கு',
  'Historical Milling Batches Log': 'கடந்த கால அரைவை தொகுதிகள் குறிப்பேடு',
  'Ledger of processed batches showing yields, parboiled parameters, and and traceability logs.': 'அரைவை தொகுதிகள், உலர் விளைச்சல் மற்றும் கண்காணிப்புப் பதிவுகள்.',
  'Search batch/variety...': 'தொகுதி/ரகத்தைத் தேடுக...',
  'Export Excel': 'எக்செல் ஏற்றுமதி',
  'Start Date': 'தொடங்கிய தேதி',
  'End Date': 'முடிவடைந்த தேதி',
  'Batch No': 'தொகுதி எண்',
  'Stage': 'நிலை',
  'Source Stock': 'மூல இருப்பு',
  'Paddy Bags': 'நெல் மூட்டைகள்',
  'Head Rice': 'முழு அரிசி',
  'Broken': 'குருணை அரிசி',
  'Yield %': 'விளைச்சல் %',
  'No production batches found.': 'அரைவை தொகுதிகள் எதுவும் காணப்படவில்லை.',
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('skp_language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('skp_language', lang);
  };

  const t = (text: string): string => {
    if (language === 'en') return text;
    
    // Exact match lookup
    const trimmed = text.trim();
    if (translationDictionary[trimmed]) {
      return translationDictionary[trimmed];
    }
    
    // Substring replace for common key phrases if possible
    let translated = text;
    for (const [enKey, taVal] of Object.entries(translationDictionary)) {
      if (enKey.length > 4 && translated.includes(enKey)) {
        translated = translated.split(enKey).join(taVal);
      }
    }
    
    return translated;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
