import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'en' | 'ta';

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (text: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

// Comprehensive English to Tamil translation dictionary
const translationDictionary: Record<string, string> = {
  // Navigation Sidebar
  'Overview Dashboard': 'கண்காணிப்பு டாஷ்போர்டு',
  'Paddy Entry': 'நெல் வரவுப் பதிவேடு',
  'Paddy Purchase': 'நெல் கொள்முதல் பில்',
  'Milling & Stock': 'அரைவை & இருப்பு',
  'Quality & Finance': 'தரம் & நிதிப் பேரேடு',
  'Labor & Wages': 'தொழிலாளர் & கூலி',
  'Voice & Insights': 'செயல்பாட்டு நுண்ணறிவு',
  'Systems & Analytics': 'அமைப்புகள் & பகுப்பாய்வு',
  'Mill Manager Account': 'ஆலை மேலாளர் கணக்கு',
  'Active Workspace': 'செயலில் உள்ள பணித்தளம்',
  
  // Tab Titles
  'Paddy Entry Register': 'நெல் வரவுப் பதிவேடு',
  'Paddy Purchase Bills': 'நெல் கொள்முதல் பில்கள்',
  'Milling Batches & Stock Logs': 'அரைவை தொகுதிகள் & இருப்பு பதிவுகள்',
  'Quality Logs & Finance Ledger': 'தரக் கட்டுப்பாட்டு பதிவுகள் & நிதிப் பேரேடு',
  'Labor Wages & Attendance Tracker': 'தொழிலாளர் ஊதியம் & வருகைப் பதிவு',
  'Executive Insights Desk': 'செயல்பாட்டு நுண்ணறிவு பிரிவு',
  'Overview Dashboard Title': 'கண்காணிப்பு டாஷ்போர்டு',

  // Dashboard Stats
  'Live Milling Overview': 'நேரடி அரைவை கண்ணோட்டம்',
  'Paddy Stock (Bags)': 'நெல் இருப்பு (மூட்டைகள்)',
  'Rice Stock (Bags)': 'அரிசி இருப்பு (மூட்டைகள்)',
  'Unprocessed arrivals': 'செயலாக்கப்படாத நெல் வரவுகள்',
  'Active Milling Batches': 'செயலில் உள்ள அரைவை தொகுதிகள்',
  'Total Dispatched Today': 'இன்று அனுப்பப்பட்ட மொத்த அரிசி',
  'Paddy Arrivals Trend': 'நெல் வரவு போக்கு',
  'Paddy Stocks by Variety': 'நெல் ரகம் வாரியாக இருப்பு',
  'Rice Storage Balances': 'அரிசி சேமிப்பக இருப்பு விவரம்',
  'Live Milling Queue & Dispatch': 'அரைவை வரிசை & வாகன அனுப்புதல்',
  'Paddy Storage Balances': 'நெல் சேமிப்பக இருப்பு விவரம்',
  'Moisture': 'ஈரப்பதம்',
  'Moisture Average': 'சராசரி ஈரப்பதம்',
  
  // Common terms / Table columns
  'Supplier': 'விற்பனையாளர்/விவசாயி',
  'Supplier Name': 'விற்பனையாளர் பெயர்',
  'Variety': 'நெல் ரகம்',
  'Paddy Variety': 'நெல் ரகம்',
  'Lorry No': 'லாரி எண்',
  'Lorry Number': 'லாரி எண்',
  'Net Wt': 'நிகர எடை',
  'Net Weight': 'நிகர எடை',
  'Net Weight (Kg)': 'நிகர எடை (கிலோ)',
  'Status': 'நிலை',
  'Bags': 'மூட்டைகள்',
  'Bag Count': 'மூட்டைகளின் எண்ணிக்கை',
  'Driver Mobile': 'ஓட்டுனர் அலைபேசி',
  'Actions': 'செயல்கள்',
  'Dispatched': 'அனுப்பப்பட்டது',
  'Milling': 'அரைவை',
  'Storage Location': 'சேமிப்பு இடம்',
  'Storage Destination': 'சேமிப்பு இலக்கு',
  'Milling Progress': 'அரைவை முன்னேற்றம்',
  'In Progress': 'செயல்பாட்டில் உள்ளது',
  'Completed': 'முடிவடைந்தது',
  'Pending Rec': 'ஒப்பீடு தேவை',
  'Reconciled': 'ஒப்பிடப்பட்டது',
  'Gross Weight (Kg)': 'மொத்த எடை (கிலோ)',
  'Tare Weight (Kg)': 'வெற்று வண்டி எடை (கிலோ)',
  'Date': 'தேதி',
  'Arrival Date': 'வந்த தேதி',
  'Time': 'நேரம்',

  // Buttons & Actions
  'New Paddy Arrival': 'புதிய நெல் வரவுப் பதிவு',
  'Save Arrival Entry': 'வரவுப் பதிவைச் சேமி',
  'Clear Form': 'படிவத்தை அழி',
  'Search by supplier or lorry...': 'விற்பனையாளர் அல்லது லாரி எண் மூலம் தேடுக...',
  'Paddy Arrival Ledger': 'நெல் வரவுப் பதிவேடு',
  'Edit': 'திருத்து',
  'Delete': 'நீக்கு',
  'Edit Entry': 'பதிவைத் திருத்து',
  'Save Invoice': 'பில்லைச் சேமி',
  'Update Purchase Invoice': 'கொள்முதல் பில்லைப் புதுப்பி',
  'Search purchases (supplier/lorry)...': 'கொள்முதல் பில்களைத் தேடுக...',
  'Procurement Analysis Note': 'கொள்முதல் பகுப்பாய்வுக் குறிப்பு',
  'Copy Previous Row': 'முந்தைய வரியை நகலெடு',
  'Print Selected': 'அச்சிடு',
  'Bulk Delete': 'ஒட்டுமொத்தமாக நீக்கு',
  'Save': 'சேமி',
  'Copy': 'நகலெடு',
  'PDF': 'PDF அச்சிடு',
  'Cancel': 'ரத்துசெய்',
  'Action': 'செயல்',
  'Submit': 'சமர்ப்பி',
  'Search': 'தேடுக',
  'Add Supplier': 'விற்பனையாளரைச் சேர்',
  'Add Variety': 'புதிய ரகம் சேர்',

  // Paddy Purchase Form Sections
  'Reconcile Paddy Entry Arrival': '1. நெல் வரவை ஒப்பிட்டுச் சரிபார்',
  'Primary Paddy variety weight & Rate': '2. முதன்மை நெல் ரக எடை & விலை',
  'Freight, Handling Charges & Payouts': '3. வண்டி வாடகை, கையாளுதல் கட்டணம் & கொடுப்பனவுகள்',
  'Select unsaved arrival entry': 'சேமிக்கப்படாத வரவுப் பதிவைத் தேர்ந்தெடுக்கவும்',
  'Multiple Loads': 'பல சுமைகள்',
  'Multiple Loads:': 'பல சுமைகள்:',
  'Second Item Option': 'இரண்டாவது ரக விருப்பம்',
  'Second Item Option:': 'இரண்டாவது ரக விருப்பம்:',
  'Extra Loads from Same Supplier': 'அதே விற்பனையாளரிடமிருந்து கூடுதல் சுமைகள்',
  'Dry Yield Recovery Analysis': 'உலர் விளைச்சல் மீட்பு பகுப்பாய்வு',
  'Average Moisture': 'சராசரி ஈரப்பதம்',
  'Lorry Freight / Rent': 'லாரி வாடகை (வண்டி வாடகை)',
  'Handling Charges (Unloading)': 'இறக்குமதி கையாளுதல் கட்டணம்',
  'Brokerage Commission': 'தரகு கமிஷன்',
  'Total Amount Paid Now': 'இப்போது செலுத்தப்பட்ட தொகை',
  'Payment Payout Status': 'கொடுப்பனவு நிலை',
  'Paid Now': 'செலுத்தப்பட்ட தொகை',
  'Rate per Bag': 'மூட்டைக்கான விலை (Rate/Bag)',
  'Rate per Ton/Quintal': 'குவிண்டால்/டன் விலை (Rate/Kg equivalent)',
  'Gross Amount': 'மொத்த தொகை',
  'Net Amount': 'நிகர தொகை',
  'Total Value': 'மொத்த மதிப்பு',
  
  // Stock and Production
  'Production Batch Controller': 'அரைவை உற்பத்தி தொகுதி கட்டுப்பாட்டாளர்',
  'Start New Batch': 'புதிய அரைவை தொகுதியைத் தொடங்கு',
  'Select Paddy Storage': 'நெல் சேமிப்பகத்தைத் தேர்ந்தெடுக்கவும்',
  'Paddy Input Quantity (Bags)': 'நெல் உள்ளீடு அளவு (மூட்டைகள்)',
  'Output Head Rice (Bags)': 'வெளியீடு தலை அரிசி (மூட்டைகள்)',
  'Output Broken Rice (Bags)': 'வெளியீடு குருணை அரிசி (மூட்டைகள்)',
  'Milling Status': 'அரைவை நிலை',
  'Active Batches': 'செயலில் உள்ள அரைவை தொகுதிகள்',
  'Historical Batches': 'கடந்த கால அரைவை தொகுதிகள்',
  'Input Paddy': 'உள்ளீடு நெல்',
  'Output Rice': 'வெளியீடு அரிசி',
  'Rice Storage': 'அரிசி சேமிப்பகம்',
  'Yield Recovery %': 'அரைவை மீட்பு சதவீதம் (%)',
  'Create Production Batch': 'அரைவை உற்பத்தித் தொகுதியை உருவாக்கு',
  'Stock Logs & Receipts': 'இருப்பு பதிவுகள் & ரசீதுகள்',
  'Dispatch Loading Tracker': 'விநியோகம் மற்றும் லாரி ஏற்றுதல் கண்காணிப்பு',
  'Log Dispatch Loading': 'புதிய லாரி ஏற்றப் பதிவைச் சேர்',
  'Log Dispatch': 'ஏற்றுதல் பதிவைச் சேமி',
  'Dispatch Register': 'ஏற்றுதல் பதிவேடு',
  'Available Paddy Stock': 'கிடைக்கக்கூடிய நெல் இருப்பு',
  'Available Rice Stock': 'கிடைக்கக்கூடிய அரிசி இருப்பு',
  'Paddy Inventory': 'நெல் சரக்கு இருப்பு',
  'Rice Inventory': 'அரிசி சரக்கு இருப்பு',

  // Quality and Finance
  'Quality Records Ledger': 'தரக் கட்டுப்பாட்டுப் பதிவேடு',
  'Log Quality Inspection': 'புதிய தரப் பரிசோதனையைப் பதிவுசெய்',
  'Inspection Date': 'பரிசோதனை தேதி',
  'Foreign Matter %': 'அயல் பொருட்கள் (%)',
  'Chalky Grains %': 'மாவுத்தன்மை அரிசி (%)',
  'Damaged / Discolored %': 'சேதமடைந்த / நிறமாற்றமடைந்த அரிசி (%)',
  'Moisture %': 'ஈரப்பதம் (%)',
  'Head Rice Recovery (HRR) %': 'முழு அரிசி மீட்பு (HRR) %',
  'Quality Evaluation': 'தர மதிப்பீடு',
  'Passed': 'தேர்ச்சி பெற்றது',
  'Needs Sorting': 'மறுசுழற்சி தேவை',
  'Rejected': 'நிராகரிக்கப்பட்டது',
  'Inspection Register': 'பரிசோதனைப் பதிவேடு',
  'Cashflow & Ledger Dashboard': 'நிதிப் பேரேடு & பணப்புழக்கக் கண்காணிப்பு',
  'Cashflow Ledger': 'பணப்புழக்கப் பேரேடு',
  'Log Transaction': 'புதிய நிதிப் பரிவர்த்தனையைப் பதிவுசெய்',
  'Transaction Type': 'பரிவர்த்தனை வகை',
  'Income (Sales, Payouts)': 'வருவாய் (விற்பனை/வரவுகள்)',
  'Expense (Purchases, Wages)': 'செலவு (கொள்முதல்/கூலி)',
  'Amount (₹)': 'தொகை (₹)',
  'Reference Details': 'குறிப்பு விவரங்கள்',
  'Save Transaction': 'பரிவர்த்தனையைச் சேமி',
  'Ledger List': 'நிதிப் பேரேட்டு பட்டியல்',
  'Summary Metrics': 'நிதிச் சுருக்க அளவீடுகள்',
  'Total Revenue': 'மொத்த வருவாய்',
  'Total Expenditures': 'மொத்த செலவினங்கள்',
  'Net Cash Margin': 'நிகர லாப வரம்பு',

  // Labor and Wages
  'Labor Force Directory': 'தொழிலாளர்கள் விபரக் குறிப்பேடு',
  'Add New Laborer': 'புதிய தொழிலாளரைச் சேர்',
  'Labor Category': 'தொழிலாளர் பிரிவு',
  'Milling Crew': 'அரைவைப் பிரிவு',
  'Loading / Unloading Crew': 'ஏற்றுதல் / இறக்குதல் பிரிவு',
  'Dryer Operations': 'உலர்த்திப் பிரிவு',
  'Maintenance / Electrician': 'பராமரிப்பு / மின்சார வல்லுநர்',
  'Daily Wage Rate (₹/day)': 'தினசரி கூலி விகிதம் (₹/நாள்)',
  'Save Employee Details': 'தொழிலாளர் விவரங்களைச் சேமி',
  'Wages & Attendance Tracker': 'வருகை மற்றும் தினசரி கூலி கண்காணிப்பு',
  'Attendance Date': 'வருகைப் பதிவு தேதி',
  'Mark Attendance & Calculate Daily Wages': 'தொழிலாளர் வருகை மற்றும் தினசரி கூலி கணக்கீடு',
  'Employee': 'தொழிலாளர்',
  'Mark Status': 'வருகை நிலை',
  'Daily Earned Wage': 'இன்றைய கூலி',
  'Save Attendance Sheet': 'வருகைப் பதிவேட்டைச் சேமி',
  'Weekly Attendance Report': 'வருகை மற்றும் கூலி அறிக்கை',
  'Present Days': 'வந்த நாட்கள்',
  'Absent Days': 'வராத நாட்கள்',
  'Total Wages Earned': 'மொத்த ஈட்டிய கூலி',
  'Mark Present': 'வருகை',
  'Mark Absent': 'விடுப்பு',
  'Half-Day': 'அரை நாள்',
  'Mark Half-Day': 'அரை நாள் வருகை',

  // Voice and Insights
  'Voice-Activated Executive Insights Desk': 'குரல்வழி செயல்பாட்டு நுண்ணறிவு பிரிவு',
  'Type or click Microphone to ask executive queries:': 'இயக்குநரின் கேள்விகளைக் கேட்க தட்டச்சு செய்யவும் அல்லது மைக்ரோஃபோனைக் கிளிக் செய்யவும்:',
  'Try asking: "What is the available stock of RNR variety?" or "Show total purchases this month."': 'கேட்டுப் பாருங்கள்: "RNR ரகத்தின் தற்போதைய இருப்பு எவ்வளவு?" அல்லது "இந்த மாத கொள்முதல் மதிப்பை காட்டு."',
  'Speak Now': 'பேசவும்',
  'Listening...': 'கேட்கிறது...',
  'Processing voice command...': 'குரல் கட்டளை செயலாக்கப்படுகிறது...',
  'Insights Desk': 'செயல்பாட்டு நுண்ணறிவு உதவிப் பிரிவு',
  'Interactive Voice Assistant': 'ஊடாடும் குரல் உதவியாளர்',
  'Send Query': 'கேள்வியை அனுப்பு',
  'Enter query...': 'கேள்வியைத் தட்டச்சு செய்க...',
  'Executive Summary Report': 'செயல்பாட்டு சுருக்க அறிக்கை',

  // UI details
  'Mill Manager': 'ஆலை மேலாளர்',
  'SKP Rice Mill': 'எஸ்.கே.பி அரிசி ஆலை',
  'SKP Admin': 'எஸ்.கே.பி நிர்வாகி',
  'Lorry Dispatch Receipt': 'லாரி ஏற்றுதல் விநியோக ரசீது',
  'Print Receipt': 'அச்சிடுக',
  'Close': 'மூடு',
  'Print Purchase Slip': 'கொள்முதல் சீட்டு அச்சிடு',
  'Print / Save PDF': 'அச்சிடு / PDF சேமி',
  'Date & Supplier': 'தேதி & விற்பனையாளர்',
  'Arriving Paddy Lorry Entry': 'லாரி நெல் வரவுப் பதிவு',
  'Enter lorry gross/tare weights, and allocate grain varieties into silos or storage yards.': 'லாரி எடை விவரங்களை உள்ளிட்டு, சேமிப்பு சிலோக்களுக்கு ஒதுக்கவும்.',
  'Operational Command Center': 'செயல்பாட்டு கட்டுப்பாட்டு மையம்',
  'loads': 'சுமைகள்',
  'bags': 'மூட்டைகள்',
  'parboiled batches': 'அரைவை தொகுதிகள்',
  'Today': 'இன்று',
  'Tons supplied': 'டன் வரவு',
  'Today Purchase': 'இன்றைய கொள்முதல்',
  'Today Processed': 'இன்றைய அரைவை',
  'Pending Supplier Balance': 'விவசாயிகள் நிலுவைத் தொகை',
  'Shipped Deliveries Today': 'இன்றைய அரிசி விநியோகம்',
  'Highest Volume Supplier': 'அதிகபட்ச கொள்முதல் விவசாயி',
  'Est. Gross Profit (Milling)': 'மதிப்பிடப்பட்ட அரைவை லாபம்',
  'Top Suppliers (By Supplied weight)': 'முன்னணி விவசாயிகள் (எடை அடிப்படையில்)',
  'Variety-wise Procurement (By weight)': 'ரகம் வாரியாக கொள்முதல் (எடை அடிப்படையில்)',
  'Live Stock & Payable Warnings': 'இருப்பு மற்றும் நிலுவை எச்சரிக்கைகள்',
  'Strategic Operations Summary': 'ஆலை செயல்பாட்டு சுருக்க உரை',
  'Stock balances and payables are in safe thresholds.': 'இருப்பு நிலவரங்கள் மற்றும் நிலுவைத் தொகைகள் பாதுகாப்பான வரம்பில் உள்ளன.',
  'Need purchase data': 'கொள்முதல் தரவு தேவை',

  // Voice & Insights Component
  'Voice-Enabled Sales Assistant': 'குரல்வழி விற்பனை உதவியாளர்',
  'Suggested Voice Format:': 'பரிந்துரைக்கப்பட்ட குரல் வடிவம்:',
  'Voice Text Capture': 'குரல் உரை பிடிப்பு',
  'Captured spoken text will print here...': 'பேசப்பட்ட உரை இங்கே அச்சிடப்படும்...',
  'Start Voice': 'குரலைத் தொடங்கு',
  'Stop': 'நிறுத்து',
  'Auto Fill Form': 'படிவத்தை தானாக நிரப்பு',
  'Clear': 'அழி',
  'Status:': 'நிலை:',
  'Sales draft compiler': 'விற்பனை வரைவுத் தொகுப்பாளர்',
  'Party Name': 'வாடிக்கையாளர் பெயர்',
  'Variety / Item': 'ரகம் / தயாரிப்பு',
  'No. of Bags': 'மூட்டைகளின் எண்ணிக்கை',
  'Rate per Bag (₹)': 'மூட்டைக்கான விலை (₹)',
  'Due Days': 'தவணை நாட்கள்',
  'Phone / WhatsApp': 'அலைபேசி / வாட்ஸ்அப்',
  'Sales Date': 'விற்பனை தேதி',
  'Estimated Total Amount:': 'மதிப்பிடப்பட்ட மொத்த தொகை:',
  'Save Sales Draft': 'விற்பனை வரைவைச் சேமி',
  'Copy WhatsApp Note': 'வாட்ஸ்அப் குறிப்பை நகலெடு',
  'Saved Local Sales Drafts': 'சேமிக்கப்பட்ட விற்பனை வரைவுகள்',
  'Clear All': 'அனைத்தையும் அழி',
  'These drafts are saved to your browser session storage. You can verify and load them into customer invoicing modules later.': 'இந்த வரைவுகள் உங்கள் உலாவி சேமிப்பகத்தில் சேமிக்கப்படும். பின்னர் அவற்றை விநியோக தொகுதியில் ஏற்றலாம்.',
  'Party': 'வாடிக்கையாளர்',
  'Rate': 'விலை',
  'Total': 'மொத்தம்',
  'No sales drafts created yet. Try the voice input!': 'விற்பனை வரைவுகள் எதுவும் இன்னும் உருவாக்கப்படவில்லை. குரல் உள்ளீட்டைப் பயன்படுத்தவும்!',
  'Operational Insights Business Dashboard': 'செயல்பாட்டு நுண்ணறிவு வணிக டாஷ்போர்டு',
  'Ask simple questions about your mill database. The rule engine generates instant financial reports, supplier analyses, and stock recommendation logs.': 'உங்கள் ஆலைத் தரவுத்தளத்தைப் பற்றிய எளிய கேள்விகளைக் கேளுங்கள். விதிகளின் அடிப்படையில் உடனடி நிதி அறிக்கைகள், விவசாயிகள் பகுப்பாய்வு மற்றும் இருப்புப் பரிந்துரைகள் உருவாக்கப்படும்.',
  'Ask a Question': 'கேள்வி கேட்கவும்',
  'e.g., who is our best supplier?': 'எ.கா: சிறந்த விவசாயி யார்?',
  'Analyze': 'பகுப்பாய்வு செய்',
  'Reset': 'மீட்டமை',
  'Quick Reports': 'உடனடி அறிக்கைகள்',
  'Today Purchases': 'இன்றைய கொள்முதல்',
  'This Month Purchases': 'இந்த மாத கொள்முதல்',
  'Best Supplier': 'சிறந்த விவசாயி',
  'Variety Purchase': 'ரகம் வாரியான கொள்முதல்',
  'Pending Balances': 'நிலுவைத் தொகைகள்',
  'Paddy Stock Levels': 'நெல் இருப்பு அளவுகள்',
  'Paddy Reorder recommendation': 'நெல் மறு ஆர்டர் பரிந்துரை',
  'Milling Yield Batch': 'சிறந்த விளைச்சல் தொகுதி',
  'Milling Batches Month': 'இந்த மாத அரைவை',
  'Absent Workers Today': 'இன்று வராத தொழிலாளர்கள்',
  'Suggestion Note:': 'பரிந்துரைக் குறிப்பு:',

  // Extra missing keys
  'Pending': 'நிலுவையில் உள்ளது',
  'Paid': 'செலுத்தப்பட்டது',
  'Partial': 'பகுதி செலுத்தப்பட்டது',
  'All Purchase Status': 'அனைத்து கொள்முதல் நிலை',
  'Entry Only': 'வரவுப் பதிவு மட்டும்',
  'Saved to Purchase': 'கொள்முதலில் சேமிக்கப்பட்டது',
  'No matching paddy entries found.': 'பொருந்தக்கூடிய நெல் வரவுகள் எதுவும் இல்லை.',
  'Filter date': 'தேதியை வடிக்க',
  'Filter party': 'விவசாயியை வடிக்க',
  'Filter lorry': 'லாரியை வடிக்க',
  'Filter weight': 'எடையை வடிக்க',
  'Filter bags': 'மூட்டைகளை வடிக்க',
  'Filter variety': 'ரகத்தை வடிக்க',
  'Filter storage': 'சேமிப்பை வடிக்க',
  'Filter recon': 'ஒப்பீட்டை வடிக்க',
  'Global search (supplier / lorry)...': 'ஒட்டுமொத்த தேடல் (விற்பனையாளர்/லாரி)...',
  'Cancel Edit': 'திருத்தலை ரத்துசெய்',
  'Update Paddy Entry': 'நெல் வரவைப் புதுப்பி',
  'Save Paddy Entry': 'நெல் வரவைச் சேமி',
  'Record Opening Paddy Balances (Silos / Godowns)': 'ஆரம்ப நெல் இருப்புகளைப் பதிவுசெய்க (சிலோஸ் / கிடங்குகள்)',
  'Initialize stock that was already filled before tracking with this application.': 'இந்த செயலி மூலம் கண்காணிக்கும் முன் ஏற்கனவே நிரப்பப்பட்ட இருப்பை உள்ளிடவும்.',
  'Silo / Godown Storage': 'சிலோ / கிடங்கு சேமிப்பு',
  'Lot Supplier / Ref': 'தொகுதி விற்பனையாளர் / குறிப்பு',
  'Save Opening Stock': 'ஆரம்ப இருப்பைச் சேமி',
  'Silo & Yard Stock Transfers': 'சிலோ மற்றும் யார்டு இருப்பு இடமாற்றங்கள்',
  'Move paddy raw lots between yards or feed silos directly.': 'யார்டுகள் அல்லது சிலோக்களுக்கு இடையே நெல் இருப்பை நேரடியாக மாற்றவும்.',
  'Transfer Date': 'மாற்றப்பட்ட தேதி',
  'From Storage': 'இருந்து (மூல சேமிப்பு)',
  'Select source': 'மூலத்தைத் தேர்ந்தெடுக்கவும்',
  'Select variety': 'ரகத்தைத் தேர்ந்தெடுக்கவும்',
  'Available Bags': 'கிடைக்கக்கூடிய மூட்டைகள்',
  'To Storage SILO': 'சேரும் சிலோ (இலக்கு)',
  'Bags to Move': 'மாற்ற வேண்டிய மூட்டைகள்',
  'Transfer Remarks': 'மாற்றுக் குறிப்புகள்',
  'Save Stock Movement': 'இருப்பு மாற்றத்தைச் சேமி',
  'Combine multiple grain lots to fulfill the 600 paddy bags parboiled requirement, and transition them into head & broken rice products.': '600 நெல் மூட்டைகளின் தேவையைப் பூர்த்தி செய்ய பல நெல் தொகுதிகளை ஒன்றிணைத்து, அவற்றை முழு மற்றும் குருணை அரிசி தயாரிப்புகளாக மாற்றவும்.',
  'Start New Batch (Deduct Paddy Stock)': 'புதிய தொகுதியைத் தொடங்கு (நெல் இருப்பைக் கழி)',
  'Milling Start Date': 'அரைவை தொடக்க தேதி',
  'Batch ID / Process No': 'தொகுதி ஐடி / செயல்முறை எண்',
  'Target Batch size (Bags)': 'இலக்கு தொகுதி அளவு (மூட்டைகள்)',
  'Presteam Timing (Min)': 'அவித்தல் நேரம் (நிமிடங்கள்)',
  'Holding Tank Tempering (Min)': 'தொட்டி பதப்படுத்துதல் (நிமிடங்கள்)',
  'LCU Tank Tempering (Hours)': 'LCU தொட்டி பதப்படுத்துதல் (மணிநேரம்)',
  'Water Soaking (Hours)': 'தண்ணீர் ஊறவைத்தல் (மணிநேரம்)',
  'Combine Paddy Stocks for Batch': 'தொகுதிக்கான நெல் இருப்புகளை இணைக்கவும்',
  'Select Silo/Godown': 'சிலோ/கிடங்கைத் தேர்ந்தெடு',
  'Select storage': 'சேமிப்பைத் தேர்ந்தெடு',
  'Available Stock (Bags)': 'கிடைக்கக்கூடிய இருப்பு (மூட்டைகள்)',
  'Add bags from source': 'மூலத்திலிருந்து மூட்டைகளைச் சேர்',
  '+ Add Source Line': '+ மூல வரியைச் சேர்',
  'Paddy Bin': 'நெல் தொட்டி (பின்)',
  'Bags Added': 'சேர்க்கப்பட்ட மூட்டைகள்',
  'Total Selected Paddy:': 'தேர்ந்தெடுக்கப்பட்ட மொத்த நெல்:',
  'Start Milling Remarks': 'அரைவை குறிப்புகள்',
  'Start Production Batch': 'அரைவை உற்பத்தித் தொகுதியைத் தொடங்கு',
  '2️⃣ Complete Milling Output (Yield & Rice Bags Creation)': '2️⃣ அரைவை வெளியீட்டை முடித்தல் (அரிசி மூட்டைகள் உருவாக்கம்)',
  'Select In-Process Batch': 'செயல்பாட்டில் உள்ள தொகுதியைத் தேர்ந்தெடு',
  'Select batch': 'தொகுதியைத் தேர்ந்தெடு',
  'Completion Date': 'முடிவடைந்த தேதி',
  'Milled Batch No': 'அரைக்கப்பட்ட தொகுதி எண்',
  'Rice storage placement': 'அரிசி சேமிப்பக இடம்',
  'Head Rice Output (Bags 26kg)': 'முழு அரிசி வெளியீடு (26 கிலோ மூட்டைகள்)',
  'Broken Rice Output (Bags 26kg)': 'குருணை அரிசி வெளியீடு (26 கிலோ மூட்டைகள்)',
  'Final Moisture %': 'இறுதி ஈரப்பதம் %',
  'Milled Grade Quality': 'அரைக்கப்பட்ட அரிசி தரம்',
  'Good': 'நன்று',
  'Excellent': 'மிக நன்று',
  'Average': 'சராசரி',
  'Needs Check': 'சரிபார்க்கப்பட வேண்டும்',
  'Poststeaming Timing (Min)': 'இரண்டாம் அவித்தல் நேரம் (நிமிடங்கள்)',
  'Mechanical Drying Cycle (Hours)': 'இயந்திர உலர்த்தும் சுழற்சி (மணிநேரம்)',
  'Output Milling Remarks': 'வெளியீட்டு அரைவைக் குறிப்புகள்',
  'Complete Batch & Create Rice Stock': 'தொகுதியை முடித்து அரிசி இருப்பை உருவாக்கு',
  'Historical Milling Batches Log': 'கடந்த கால அரைவை தொகுதிகள் குறிப்பேடு',
  'Ledger of processed batches showing yields, parboiled parameters, and and traceability logs.': 'அரைவை தொகுதிகள், உலர் விளைச்சல் மற்றும் கண்காணிப்புப் பதிவுகள்.',
  'Search batch/variety...': 'தொகுதி/ரகத்தைத் தேடுக...',
  'Export Excel': 'எக்செல் ஏற்றுமதி',
  'Start Date': 'தொடங்கிய தேதி',
  'End Date': 'முடிவடைந்த தேதி',
  'Batch No': 'தொகுதி எண்',
  'Stage': 'நிலை',
  'Source Stock': 'மூல இருப்பு',
  'Paddy Bags': 'நெல் மூட்டைகள்',
  'Head Rice': 'முழு அரிசி',
  'Broken': 'குருணை அரிசி',
  'Yield %': 'விளைச்சல் %',
  'No production batches found.': 'அரைவை தொகுதிகள் எதுவும் காணப்படவில்லை.',

  "Please add employees first.": "முதலில் பணியாளர்களைச் சேர்க்கவும்.",
  "All marked present!": "அனைவரும் வந்ததாகப் பதிவு செய்யப்பட்டது!",
  "No attendance marked for this date.": "இந்த தேதியில் வருகை பதிவு செய்யப்படவில்லை.",
  "Daily log cleared.": "தினசரி பதிவு அழிக்கப்பட்டது.",
  "Please fill name and wage details.": "பெயர் மற்றும் கூலி விவரங்களை உள்ளிடவும்.",
  "Employee profile updated!": "பணியாளர் விவரங்கள் புதுப்பிக்கப்பட்டன!",
  "Employee added successfully!": "பணியாளர் வெற்றிகரமாக சேர்க்கப்பட்டார்!",
  "General": "பொது",
  "Milling Attendance Yard Board": "அரைவை வருகைப் பதிவுப் பலகை",
  "Daily labor tracking. Use the \"Mark All Present\" button for bulk shifts, and adjust exceptions.": "தினசரி தொழிலாளர் வருகை கண்காணிப்பு. ஒட்டுமொத்தப் பதிவிற்கு 'அனைவரும் வருகை' பொத்தானைப் பயன்படுத்தவும்.",
  "Daily Date": "தினசரி தேதி",
  "Mark All Present": "அனைவரும் வருகை",
  "Clear Today Attendance": "இன்றைய வருகையை அழி",
  "Monthly Payout Sheet": "மாதாந்திர கூலி பட்டியல்",
  "Search employee / status...": "பணியாளர் அல்லது வருகையைத் தேடுக...",
  "All Employees": "அனைத்து தொழிலாளர்கள்",
  "All Statuses": "அனைத்து நிலைகளும்",
  "Present": "வருகை",
  "Absent": "விடுப்பு",
  "Half Day": "அரை நாள்",
  "Not Marked": "பதிவு செய்யப்படவில்லை",
  "Roster Strength": "பணியாளர் எண்ணிக்கை",
  "Marked": "பதிவு செய்யப்பட்டது",
  "Unmarked": "பதிவு செய்யப்படாதது",
  "Phone": "அலைபேசி",
  "Wage": "கூலி",
  "Earned": "ஈட்டியது",
  "Sheet": "பட்டியல்",
  "Employee Master Roster": "தொழிலாளர்கள் மாஸ்டர் பட்டியல்",
  "Add or edit milling workers. Use Up/Down buttons to re-order the payroll index.": "பணியாளர்களைச் சேர்க்கவும் அல்லது திருத்தவும். வரிசையை மாற்ற மேல்/கீழ் பொத்தான்களைப் பயன்படுத்தவும்.",
  "Worker Name": "தொழிலாளர் பெயர்",
  "Phone Number": "தொலைபேசி எண்",
  "Salary Type": "சம்பள வகை",
  "Shift Type": "ஷிப்ட் வகை",
  "12 Hr": "12 மணிநேரம்",
  "24 Hr": "24 மணிநேரம்",
  "Wages Amount (₹)": "கூலித் தொகை (₹)",
  "Update Employee Profile": "பணியாளர் விவரங்களைப் புதுப்பி",
  "Save Employee": "பணியாளரைச் சேமி",
  "S.No": "வ.எண்",
  "Employee Name": "பணியாளர் பெயர்",
  "Shift Length": "ஷிப்ட் நேரம்",
  "Wages": "கூலி",
  "Sequence": "வரிசை",
  "Current Paddy Stock": "தற்போதைய நெல் இருப்பு",
  "available bags in silos/godowns": "சிலோஸ்/கிடங்குகளில் உள்ள மூட்டைகள்",
  "Current Rice Stock": "தற்போதைய அரிசி இருப்பு",
  "available processed bags": "அரைக்கப்பட்ட அரிசி மூட்டைகள்",
  "accounts outstanding": "நிலுவையில் உள்ள கணக்குகள்",
  "vehicle loading logs": "வாகன ஏற்றுதல் பதிவுகள்",
  "derived from market selling averages": "சந்தை விற்பனை சராசரியிலிருந்து கணக்கிடப்பட்டது",
  "Enter supplier name first.": "முதலில் விவசாயி பெயரை உள்ளிடவும்.",
  "New supplier saved!": "புதிய விவசாயி சேமிக்கப்பட்டார்!",
  "Please select a Supplier / Party.": "விவசாயி/வாடிக்கையாளரைத் தேர்ந்தெடுக்கவும்.",
  "Net weight is zero. Check load and empty weights.": "நிகர எடை பூஜ்ஜியமாக உள்ளது. வண்டி மற்றும் வெற்று எடையைச் சரிபார்க்கவும்.",
  "Paddy entry updated successfully!": "நெல் வரவு வெற்றிகரமாக புதுப்பிக்கப்பட்டது!",
  "Paddy entry saved successfully!": "நெல் வரவு வெற்றிகரமாக சேமிக்கப்பட்டது!",
  "Error saving paddy entry.": "நெல் வரவைச் சேமிப்பதில் பிழை.",
  "Party / Supplier": "வாடிக்கையாளர் / விவசாயி",
  "Select Supplier": "விவசாயியைத் தேர்ந்தெடுக்கவும்",
  "Quick Add Supplier": "விவசாயியை விரைவாகச் சேர்",
  "Save Supplier": "விவசாயியைச் சேமி",
  "Lorry & Weighment Details": "லாரி மற்றும் எடை விவரங்கள்",
  "Lorry / Vehicle No": "லாரி / வாகன எண்",
  "Gross Weight (Load Kg)": "மொத்த எடை (வண்டியுடன் கிலோ)",
  "Tare Weight (Empty Kg)": "வெற்று வண்டி எடை (கிலோ)",
  "No. of Bags / உருப்படி": "மூட்டைகளின் எண்ணிக்கை / உருப்படி",
  "Variety, Allocation & Settlement Status": "நெல் ரகம், இருப்பிடம் மற்றும் கட்டண நிலை",
  "Storage Area / SILO": "சேமிப்பு பகுதி / சிலோ",
  "Paddy Storage 1": "நெல் சேமிப்பகம் 1",
  "Gunny Weight Base (Kg)": "மூட்டை வெற்று எடை (கிலோ)",
  "Wages Rate per Gunny (₹)": "மூட்டைக்கான கூலி விகிதம் (₹)",
  "Initial Payment Status": "ஆரம்ப கட்டண நிலை",
  "Calculated Bags": "கணக்கிடப்பட்ட மூட்டைகள்",
  "Leftover Weight": "மீதமுள்ள எடை",
  "Estimated Cost": "மதிப்பிடப்பட்ட செலவு",
  "Saved Paddy Entry Register": "சேமிக்கப்பட்ட நெல் வரவுப் பதிவேடு",
  "Ledger of arriving paddy trucks before double-entry reconciliation.": "இரட்டைப் பதிவு சரிபார்ப்பிற்கு முன் வந்த நெல் லாரிகளின் பதிவேடு.",
  "Today Entries": "இன்றைய வரவுகள்",
  "All Entries": "அனைத்து வரவுகள்",
  "Gross (kg)": "மொத்த எடை (கிலோ)",
  "Tare (kg)": "வெற்று எடை (கிலோ)",
  "Storage": "சேமிப்பிடம்",
  "Cost": "செலவு",
  "Recon Status": "சரிபார்ப்பு நிலை",
  "New variety saved!": "புதிய நெல் ரகம் சேமிக்கப்பட்டது!",
  "Please link a saved Paddy Entry load first.": "முதலில் சேமிக்கப்பட்ட நெல் வரவை இணைக்கவும்.",
  "Supplier, Net weight and Rate must be valid.": "விவசாயி, நிகர எடை மற்றும் விலை சரியாக இருக்க வேண்டும்.",
  "Purchase record updated!": "கொள்முதல் பதிவு புதுப்பிக்கப்பட்டது!",
  "Purchase saved!": "கொள்முதல் சேமிக்கப்பட்டது!",
  "Error saving purchase.": "கொள்முதல் சேமிப்பதில் பிழை.",
  "Please select a target row first using the checkbox.": "முதலில் தேர்வுப்பெட்டியைப் பயன்படுத்தி ஒரு வரியைத் தேர்ந்தெடுக்கவும்.",
  "No previous row available to copy from.": "நகலெடுக்க முந்தைய வரி எதுவும் இல்லை.",
  "Copied values from preceding row.": "முந்தைய வரியிலிருந்து மதிப்புகள் நகலெடுக்கப்பட்டன.",
  "Please select rows to delete.": "நீக்க வேண்டிய வரிகளைத் தேர்ந்தெடுக்கவும்.",
  "Enter passcode to delete selected rows:": "தேர்ந்தெடுக்கப்பட்ட வரிகளை நீக்க கடவுச்சொல்லை உள்ளிடவும்:",
  "Wrong passcode.": "தவறான கடவுச்சொல்.",
  "Selected rows deleted.": "தேர்ந்தெடுக்கப்பட்ட வரிகள் நீக்கப்பட்டன.",
  "Excel row saved successfully!": "எக்செல் வரி வெற்றிகரமாக சேமிக்கப்பட்டது!",
  "Failed to save excel row.": "எக்செல் வரியைச் சேமிக்க முடியவில்லை.",
  "Select rows to print first.": "முதலில் அச்சிட வேண்டிய வரிகளைத் தேர்ந்தெடுக்கவும்.",
  "Double-Entry Paddy Purchase": "இரட்டைப் பதிவு நெல் கொள்முதல்",
  "Reconcile arriving lorry slip registers, add secondary variety options, Waadagai/unloading expenses, and record transactions.": "லாரி வரவுச் சீட்டுகளை ஒப்பிட்டு, கூடுதல் ரகங்கள், வாடகை மற்றும் கையாளுதல் செலவுகளைப் பதிவு செய்யவும்.",
  "Purchase Date": "கொள்முதல் தேதி",
  "Link Paddy Entry Arrival Slip": "நெல் வரவுச் சீட்டை இணைக்கவும்",
  "Bill / Invoice No": "பில் / விலைப்பட்டியல் எண்",
  "Auto Bill No": "தானியங்கி பில் எண்",
  "Add Supplier Name": "விவசாயி பெயரைச் சேர்க்கவும்",
  "New Supplier": "புதிய விவசாயி",
  "Add": "சேர்",
  "Primary Lorry No": "முதன்மை லாரி எண்",
  "Add Variety Name": "நெல் ரகப் பெயரைச் சேர்க்கவும்",
  "New Variety": "புதிய ரகம்",
  "Discount Weight (Kg)": "கழிவு எடை (கிலோ)",
  "Primary Gunny base (Kg)": "மூட்டை வெற்று எடை (கிலோ)",
  "Rate per Gunny (₹)": "மூட்டைக்கான கூலி விகிதம் (₹)",
  "வாடகை / Freight": "வண்டி வாடகை / Freight",
  "கூலி + கமிஷன்": "கூலி + கமிஷன்",
  "சாப்பாடு / Driver Food": "ஓட்டுநர் சாப்பாடு",
  "Cess / Other Tax": "செஸ் / இதர வரி",
  "உடன்பற்று / Spot Paid": "உடனடிப் பணம் / Spot Paid",
  "Payment Status": "கட்டண நிலை",
  "Paid Date": "செலுத்தப்பட்ட தேதி",
  "Milling Value": "அரைவை மதிப்பு",
  "Payable Balance": "செலுத்த வேண்டிய நிலுவை",
  "Smart Assist Warnings": "ஸ்மார்ட் உதவி எச்சரிக்கைகள்",
  "Save + Open Slip PDF": "சேமி + பில் PDF திற",
  "Saved Paddy Purchase Register": "சேமிக்கப்பட்ட நெல் கொள்முதல் பதிவேடு",
  "Reconciled bills ready for accounting, print operations, and ledger sync.": "ஒப்பிடப்பட்ட பில்கள் கணக்கியல் மற்றும் அச்சிடலுக்குத் தயாராக உள்ளன.",
  "All Purchases": "அனைத்து கொள்முதல்கள்",
  "Excel Grid": "எக்செல் அட்டவணை",
  "Analytics": "பகுப்பாய்வு",
  "Bill No": "பில் எண்",
  "Primary Lorry": "முதன்மை லாரி",
  "Gunny base": "மூட்டை எடை",
  "Wages/Rate": "கூலி/விலை",
  "Invoice Value": "பில் மதிப்பு",
  "Outstanding": "நிலுவை",
  "No matching purchase invoices found.": "பொருந்தக்கூடிய கொள்முதல் பில்கள் எதுவும் இல்லை.",
  "Excel Search...": "எக்செல் தேடல்...",
  "All Suppliers": "அனைத்து விவசாயிகளும்",
  "All Varieties": "அனைத்து ரகங்களும்",
  "Please enter a valid number of bags.": "முறையான மூட்டைகளின் எண்ணிக்கையை உள்ளிடவும்.",
  "Please enter a party/customer name.": "வாடிக்கையாளர் பெயரை உள்ளிடவும்.",
  "Please enter a target godown.": "இலக்கு கிடங்கை உள்ளிடவும்.",
  "Dispatch loading registered successfully!": "வாகனம் ஏற்றுதல் வெற்றிகரமாக பதிவு செய்யப்பட்டது!",
  "Please select a production batch first.": "முதலில் அரைவை உற்பத்தித் தொகுதியைத் தேர்ந்தெடுக்கவும்.",
  "Quality record saved successfully!": "தரக் கட்டுப்பாட்டுப் பதிவு வெற்றிகரமாக சேமிக்கப்பட்டது!",
  "Error saving quality log.": "தரக் கட்டுப்பாட்டுப் பதிவைச் சேமிப்பதில் பிழை.",
  "Quality Control Logs": "தரக் கட்டுப்பாட்டுப் பதிவுகள்",
  "Cashflow Dashboard": "பணப்புழக்கக் கண்காணிப்பு",
  "Loading Dispatches": "வாகன ஏற்றுதல் விநியோகங்கள்",
  "Quality & Yield Tracking": "தரம் மற்றும் விளைச்சல் கண்காணிப்பு",
  "Trace parboiled rice moisture levels, stickiness, head recovery ratios, and client cooking logs directly linked to production batches.": "அரிசி ஈரப்பதம், ஒட்டும் தன்மை, முழு அரிசி மீட்பு விகிதம் மற்றும் சமையல் தரத்தைக் கண்காணிக்கவும்.",
  "Select Batch": "தொகுதியைத் தேர்ந்தெடு",
  "Select milling batch": "அரைவை உற்பத்தித் தொகுதியைத் தேர்ந்தெடு",
  "Date Recorded": "பதிவு செய்யப்பட்ட தேதி",
  "Supplier Source Lots": "விவசாயி தொகுதி குறிப்பு",
  "Paddy Bags Input": "நெல் மூட்டைகள் உள்ளீடு",
  "Head Rice Bags (26kg)": "முழு அரிசி மூட்டைகள் (26 கிலோ)",
  "Broken Rice Bags (26kg)": "குருணை அரிசி மூட்டைகள் (26 கிலோ)",
  "Cooking Quality": "சமையல் தரம்",
  "Needs Improvement": "மேம்படுத்தப்பட வேண்டும்",
  "Stickiness": "ஒட்டும் தன்மை",
  "Low": "குறைவு",
  "Medium": "நடுத்தரம்",
  "High": "அதிகம்",
  "Elongation / Rice Length": "அரிசி நீளம் (Elongation)",
  "Poor": "மோசம்",
  "Customer / Wholesaler Feedback": "வாடிக்கையாளர் / மொத்த வியாபாரி கருத்து",
  "Milling General Notes": "அரைவைப் பொதுக் குறிப்புகள்",
  "Head Yield Recovery": "முழு அரிசி விளைச்சல்",
  "Broken Recovery": "குருணை அரிசி விளைச்சல்",
  "Total Recovered": "மொத்த அரிசி விளைச்சல்",
  "Save Quality Log": "தரப் பரிசோதனையைச் சேமி",
  "Reset Form": "படிவத்தை மீட்டமை",
  "Quality History & Traceability Logs": "தரக் கட்டுப்பாடு மற்றும் கண்காணிப்புப் பதிவுகள்",
  "View overall average recovery and traces to best parboiling months.": "சராசரி விளைச்சல் மற்றும் சிறந்த அரைவை மாதங்களின் விவரங்களைக் காண்க.",
  "Export Quality Excel": "தரப் பதிவுகளை எக்செல் செய்க",
  "Avg Head Recovery": "சராசரி முழு அரிசி விளைச்சல்",
  "Avg Broken Recovery": "சராசரி குருணை அரிசி விளைச்சல்",
  "Best Supplier Lot": "சிறந்த உலர் விளைச்சல் தொகுதி",
  "Best Purchase Month": "சிறந்த கொள்முதல் மாதம்",
  "Search quality / batch / lot / feedback": "தரம், தொகுதி அல்லது கருத்து மூலம் தேடுக...",
  "Source Storage": "மூல சேமிப்பிடம்",
  "Paddy": "நெல்",
  "Head Bags": "முழு அரிசி மூட்டைகள்",
  "Broken Bags": "குருணை அரிசி மூட்டைகள்",
  "Head %": "முழு அரிசி %",
  "Broken %": "குருணை அரிசி %",
  "Feedback/Notes": "கருத்துகள்/குறிப்புகள்",
  "No matching quality records logged.": "தரப் பதிவுகள் எதுவும் இல்லை.",
  "Financial Cashflow Dashboard": "நிதி மற்றும் பணப்புழக்கக் கண்காணிப்பு",
  "Owner Command View: Tracks live cash flows, processing expenditures, finished stock valuation, and gross profit estimates.": "நிர்வாகப் பார்வை: பணப்புழக்கம், உற்பத்திச் செலவுகள், அரிசி இருப்பு மதிப்பு மற்றும் லாப மதிப்பீடு.",
  "Filter Month": "மாத வாரியாக வடிக்க",
  "Head Selling Rate / 26kg": "முழு அரிசி விற்பனை விலை (26 கிலோ)",
  "Broken Selling Rate / 26kg": "குருணை அரிசி விற்பனை விலை (26 கிலோ)",
  "Processing Cost / Paddy Bag": "நெல் மூட்டைக்கான அரைவைச் செலவு",
  "Export Financial Ledger": "நிதிப் பேரேட்டை எக்செல் செய்க",
  "Clear Month": "வடிகட்டியதை நீக்கு",
  "Paddy Purchase Value": "நெல் கொள்முதல் மதிப்பு",
  "Paid to Suppliers": "விவசாயிகளுக்கு வழங்கியது",
  "Outstanding Liabilities": "செலுத்த வேண்டிய நிலுவை",
  "Processing Overheads": "அரைவை உற்பத்திச் செலவுகள்",
  "Milled Output Value": "அரைக்கப்பட்ட அரிசி மதிப்பு",
  "Available Stock Value": "இருப்பு அரிசி மதிப்பு",
  "Shipped Loaded Value": "விநியோகிக்கப்பட்ட அரிசி மதிப்பு",
  "Est. Monthly Gross Profit": "மதிப்பிடப்பட்ட மாதாந்திர நிகர லாபம்",
  "Supplier Outstanding Balance Ledger": "விவசாயிகள் நிலுவைத் தொகை பேரேடு",
  "Loads": "சுமைகள்",
  "Purchase Value": "கொள்முதல் மதிப்பு",
  "Cash Paid": "செலுத்திய ரொக்கம்",
  "No supplier balances logged.": "விவசாயிகள் நிலுவை விவரங்கள் எதுவும் இல்லை.",
  "Milling Batch Profitability Estimates": "அரைவை தொகுதி வாரியான லாப மதிப்பீடு",
  "Batch": "தொகுதி",
  "Paddy (Bags)": "நெல் (மூட்டைகள்)",
  "Output Value": "வெளியீட்டு அரிசி மதிப்பு",
  "Process Overheads": "உற்பத்திச் செலவு",
  "No completed batches in filtered date scope.": "குறிப்பிட்ட தேதியில் முடிந்த தொகுதிகள் எதுவும் இல்லை.",
  "Loading Dispatch Tracker": "வாகன விநியோகக் கண்காணிப்பு",
  "Record customer sales deliveries and godown stock transfer dispatches of processed rice bags.": "வாடிக்கையாளர் விற்பனை விநியோகம் மற்றும் கிடங்கு மாற்றங்களை இங்கே பதிவு செய்யவும்.",
  "Dispatch / Loading Form": "வாகனம் ஏற்றுதல் படிவம்",
  "Movement Type": "பரிமாற்ற வகை",
  "Customer Delivery (Sale)": "வாடிக்கையாளர் விநியோகம் (விற்பனை)",
  "Godown Transfer": "கிடங்கு மாற்றுதல்",
  "Customer / Party Name": "வாடிக்கையாளர் / நபர் பெயர்",
  "To Storage Godown": "இலக்கு கிடங்கு",
  "Lorry / Vehicle Number": "லாரி / வாகன எண்",
  "From Storage Source": "மூல அரிசி சேமிப்பிடம்",
  "Lot No / Batch Ref": "தொகுதி எண் / குறிப்பு எண்",
  "Rice Variety": "அரிசி ரகம்",
  "Product Grade / Packing": "அரிசி தரம் / பேக்கிங்",
  "Bags Count": "மூட்டைகளின் எண்ணிக்கை",
  "Save Dispatch Record": "விநியோகப் பதிவைச் சேமி",
  "Historic Loading Dispatches": "கடந்த கால வாகன ஏற்றுதல் பதிவுகள்",
  "Type": "வகை",
  "Destination / Party": "வாடிக்கையாளர் / சேருமிடம்",
  "Storage Source": "மூல சேமிப்பிடம்",
  "Product": "தயாரிப்பு",
  "No loading dispatches recorded yet.": "விநியோகப் பதிவுகள் எதுவும் இல்லை.",
  "Please fill Storage/Silo, Variety, and Bags.": "கிடங்கு, நெல் ரகம் மற்றும் மூட்டைகளை உள்ளிடவும்.",
  "Opening stock recorded!": "ஆரம்ப இருப்பு பதிவு செய்யப்பட்டது!",
  "Fill source, target, variety and bags.": "மூலம், இலக்கு, நெல் ரகம் மற்றும் மூட்டைகளை உள்ளிடவும்.",
  "Transfer request exceeds available stock. Available: ${av} Bags.": "மாற்றுக் கோரிக்கை இருப்பை விட அதிகமாக உள்ளது. இருப்பு: ${av} மூட்டைகள்.",
  "Stock movement completed!": "இருப்பு இடமாற்றம் முடிந்தது!",
  "Select source silo/yard, variety and bags count.": "மூல சிலோ/யார்டு, நெல் ரகம் மற்றும் மூட்டைகளை உள்ளிடவும்.",
  "Bags exceed currently available stock. Available: ${available} Bags.": "உள்ளிடப்பட்ட மூட்டைகள் இருப்பை விட அதிகமாக உள்ளன. இருப்பு: ${available} மூட்டைகள்.",
  "Please add at least one source line.": "குறைந்தது ஒரு மூல வரியையாவது சேர்க்கவும்.",
  "Total selected paddy bags (${totalBags}) must match the target batch size (${prodTargetBags} Bags).": "தேர்ந்தெடுக்கப்பட்ட மொத்த நெல் மூட்டைகள் (${totalBags}) இலக்கு தொகுதி அளவிற்கு (${prodTargetBags} மூட்டைகள்) சமமாக இருக்க வேண்டும்.",
  "Production Batch ${bNo} started successfully! Paddy stock is now blocked.": "உற்பத்தித் தொகுதி ${bNo} வெற்றிகரமாகத் தொடங்கியது! நெல் இருப்பு கழிக்கப்பட்டது.",
  "Please select an in-process batch.": "செயல்பாட்டில் உள்ள தொகுதியைத் தேர்ந்தெடுக்கவும்.",
  "Please fill Head/Broken output rice bags.": "முழு மற்றும் குருணை அரிசி வெளியீட்டு மூட்டைகளை உள்ளிடவும்.",
  "Production batch milling output recorded. Rice stock has been populated!": "உற்பத்தித் தொகுதி வெளியீடு பதிவு செய்யப்பட்டது. அரிசி இருப்பு சேர்க்கப்பட்டது!",
  "📊 Stock Overview": "📊 இருப்பு விவரம்",
  "➕ Record Opening Stock": "➕ ஆரம்ப இருப்புப் பதிவு",
  "🔁 Storage Transfers": "🔁 கிடங்கு இடமாற்றங்கள்",
  "⚙️ Production Milling": "⚙️ அரைவை உற்பத்தி",
  "Live Paddy & Rice Stock Control": "நேரடி நெல் மற்றும் அரிசி இருப்பு மேலாண்மை",
  "View real-time balances across Silos, Godowns, and processed rice bins.": "சிலோஸ், கிடங்குகள் மற்றும் அரிசி சேமிப்புப் பெட்டிகளின் இருப்பை உடனுக்குடன் காணவும்.",
  "Search storage...": "கிடங்கு/சிலோவைத் தேடுக...",
  "Paddy Stocks by Storage Bins": "சிலோஸ் வாரியாக நெல் இருப்பு",
  "Storage Place": "சேமிப்பு இடம்",
  "Live Stock (Bags)": "தற்போதைய இருப்பு (மூட்டைகள்)",
  "No paddy stocks found.": "நெல் இருப்பு எதுவும் காணப்படவில்லை.",
  "Processed Rice Stock balances": "அரைக்கப்பட்ட அரிசி இருப்புகள்",
  "Rice Bin / Storage": "அரிசி சேமிப்பிடம்",
  "Stock (Bags)": "இருப்பு (மூட்டைகள்)",
  "No rice outputs available.": "அரிசி வெளியீடு எதுவும் இல்லை.",
  "Remarks / Reason": "குறிப்புகள் / காரணம்",
  "Remove": "நீக்கு",
  "Complete": "முடிவு",
  "Please fill Party, Variety, Bags and Rate before saving.": "தயவுசெய்து நபர், ரகம், மூட்டைகள் மற்றும் விலையை உள்ளிடவும்.",
  "Sales draft saved locally!": "விற்பனை வரைவு வெற்றிகரமாக சேமிக்கப்பட்டது!",
  "WhatsApp message copied to clipboard!": "வாட்ஸ்அப் செய்தி நகலெடுக்கப்பட்டது!",
  "RNR Rice": "RNR அரிசி",
  "BPT Rice": "BPT அரிசி",
  "CO 55 Rice": "CO 55 அரிசி",
  "White Ponni Rice": "வெள்ளை பொன்னி அரிசி",
  "Broken Rice": "குருணை அரிசி",
  "Raw vs Milled Inventory": "நெல் மற்றும் அரிசி இருப்பு ஒப்பீடு",
  "Milling Yield Performance": "அரைவை விளைச்சல் திறன்",
  "Daily Procurement Trend": "தினசரி கொள்முதல் போக்கு",
  "Target Yield": "இலக்கு விளைச்சல்",
  "Last 5 Batches": "கடந்த 5 தொகுதிகள்",
  "Bags Purchased": "கொள்முதல் செய்யப்பட்ட மூட்டைகள்",
  "Paddy Stock": "நெல் இருப்பு",
  "Rice Stock": "அரிசி இருப்பு",
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('skp_language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('skp_language', lang);
  };

  const t = (text: string): string => {
    if (language === 'en') return text;
    
    // Exact match lookup
    const trimmed = text.trim();
    if (translationDictionary[trimmed]) {
      return translationDictionary[trimmed];
    }
    
    // Substring replace for common key phrases if possible
    let translated = text;
    for (const [enKey, taVal] of Object.entries(translationDictionary)) {
      if (enKey.length > 4 && translated.includes(enKey)) {
        translated = translated.split(enKey).join(taVal);
      }
    }
    
    return translated;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
